// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-vmware
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"context"
	"errors"
	"fmt"

	"github.com/atc0005/go-nagios"

	"github.com/atc0005/check-vmware/internal/config"
	"github.com/atc0005/check-vmware/internal/vsphere"

	zlog "github.com/rs/zerolog/log"
)

//go:generate go-winres make --product-version=git-tag --file-version=git-tag

func main() {

	plugin := nagios.NewPlugin()

	// defer this from the start so it is the last deferred function to run
	defer plugin.ReturnCheckResults()

	// Annotate all errors (if any) with remediation advice just before ending
	// plugin execution.
	defer vsphere.AnnotateError(plugin)

	// Setup configuration by parsing user-provided flags. Note plugin type so
	// that only applicable CLI flags are exposed and any plugin-specific
	// settings are applied.
	cfg, cfgErr := config.New(config.PluginType{VirtualMachinePowerCycleUptime: true})
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case cfgErr != nil:
		// We're using the standalone Err function from rs/zerolog/log as we
		// do not have a working configuration.
		zlog.Err(cfgErr).Msg("Error initializing application")
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateUNKNOWNLabel,
		)
		plugin.AddError(cfgErr)
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode

		return
	}

	// Enable library-level logging if debug or greater logging level is
	// enabled app-wide.
	handleLibraryLogging()

	// Set context deadline equal to user-specified timeout value for plugin
	// runtime/execution.
	ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeout())
	defer cancel()

	// Record thresholds for use as Nagios "Long Service Output" content. This
	// content is shown in the detailed web UI and in notifications generated
	// by Nagios.
	plugin.CriticalThreshold = fmt.Sprintf(
		"%d days Virtual Machine uptime",
		cfg.VMPowerCycleUptimeCritical,
	)

	plugin.WarningThreshold = fmt.Sprintf(
		"%d days Virtual Machine uptime",
		cfg.VMPowerCycleUptimeWarning,
	)

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		plugin.BrandingCallback = config.Branding("Notification generated by ")
	}

	log := cfg.Log.With().
		Str("included_resource_pools", cfg.IncludedResourcePools.String()).
		Str("excluded_resource_pools", cfg.ExcludedResourcePools.String()).
		Str("ignored_vms", cfg.IgnoredVMs.String()).
		Logger()

	log.Debug().Msg("Logging into vSphere environment")
	c, loginErr := vsphere.Login(
		ctx, cfg.Server, cfg.Port, cfg.TrustCert,
		cfg.Username, cfg.Domain, cfg.Password,
		cfg.UserAgent(),
	)
	if loginErr != nil {
		log.Error().Err(loginErr).Msgf("error logging into %s", cfg.Server)

		plugin.AddError(loginErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error logging into %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Successfully logged into vSphere environment")

	defer func() {
		if err := c.Logout(ctx); err != nil {
			log.Error().
				Err(err).
				Msg("failed to logout")
		}
	}()

	log.Debug().Msg("Performing initial filtering of vms")
	vmsFilterOptions := vsphere.VMsFilterOptions{
		ResourcePoolsIncluded:       cfg.IncludedResourcePools,
		ResourcePoolsExcluded:       cfg.ExcludedResourcePools,
		FoldersIncluded:             cfg.IncludedFolders,
		FoldersExcluded:             cfg.ExcludedFolders,
		VirtualMachineNamesExcluded: cfg.IgnoredVMs,
		IncludePoweredOff:           cfg.PoweredOff,
	}
	vmsFilterResults, vmsFilterErr := vsphere.FilterVMs(
		ctx,
		c.Client,
		vmsFilterOptions,
	)
	if vmsFilterErr != nil {
		log.Error().Err(vmsFilterErr).Msg(
			"error filtering VMs",
		)

		plugin.AddError(vmsFilterErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error filtering VMs",
			nagios.StateCRITICALLabel,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Finished initial filtering of vms")

	// here we diverge from other plugins

	log.Debug().Msg("Generate VM power cycle uptime summary")
	uptimeSummary := vsphere.GetVMPowerCycleUptimeStatusSummary(
		vmsFilterResults.VMsAfterFiltering(),
		cfg.VMPowerCycleUptimeWarning,
		cfg.VMPowerCycleUptimeCritical,
	)

	log.Debug().Msg("Compiling Performance Data details")

	pd := append(
		vsphere.VMFilterResultsPerfData(vmsFilterResults),
		[]nagios.PerformanceData{
			// The `time` (runtime) metric is appended at plugin exit, so do not
			// duplicate it here.
			{
				Label: "vms_with_critical_power_uptime",
				Value: fmt.Sprintf("%d", len(uptimeSummary.VMsCritical)),
			},
			{
				Label: "vms_with_warning_power_uptime",
				Value: fmt.Sprintf("%d", len(uptimeSummary.VMsWarning)),
			},
		}...,
	)

	if err := plugin.AddPerfData(false, pd...); err != nil {
		log.Error().
			Err(err).
			Msg("failed to add performance data")

		// Surface the error in plugin output.
		plugin.AddError(err)

		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Failed to process performance data metrics",
			nagios.StateUNKNOWNLabel,
		)

		return
	}

	// Update logger with new performance data related fields
	log = log.With().
		Int("resource_pools_evaluated", vmsFilterResults.NumRPsAfterFiltering()).
		Int("vms_total", vmsFilterResults.NumVMsAll()).
		Int("vms_after_filtering", vmsFilterResults.NumVMsAfterFiltering()).
		Int("vms_excluded_by_name", vmsFilterResults.NumVMsExcludedByName()).
		Int("vms_excluded_by_power_state", vmsFilterResults.NumVMsExcludedByPowerState()).
		Int("num_vms_with_critical_power_uptime", len(uptimeSummary.VMsCritical)).
		Int("num_vms_with_warning_power_uptime", len(uptimeSummary.VMsWarning)).
		Logger()

	log.Debug().Msg("Evaluating VM power cycle uptime")
	switch {
	case len(uptimeSummary.VMsCritical) > 0:

		log.Error().
			Str("virtual_machines_with_high_uptime", uptimeSummary.VMNames()).
			Msg("VMs crossed power cycle uptime thresholds")

		plugin.AddError(vsphere.ErrVirtualMachinePowerCycleUptimeThresholdCrossed)

		plugin.ServiceOutput = vsphere.VMPowerCycleUptimeOneLineCheckSummary(
			nagios.StateCRITICALLabel,
			vmsFilterResults,
			uptimeSummary,
		)

		plugin.LongServiceOutput = vsphere.VMPowerCycleUptimeReport(
			c.Client,
			vmsFilterOptions,
			vmsFilterResults,
			uptimeSummary,
		)

		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return

	case len(uptimeSummary.VMsWarning) > 0:

		log.Error().
			Str("virtual_machines_with_high_uptime", uptimeSummary.VMNames()).
			Msg("VMs crossed power cycle uptime thresholds")

		plugin.AddError(vsphere.ErrVirtualMachinePowerCycleUptimeThresholdCrossed)

		plugin.ServiceOutput = vsphere.VMPowerCycleUptimeOneLineCheckSummary(
			nagios.StateWARNINGLabel,
			vmsFilterResults,
			uptimeSummary,
		)

		plugin.LongServiceOutput = vsphere.VMPowerCycleUptimeReport(
			c.Client,
			vmsFilterOptions,
			vmsFilterResults,
			uptimeSummary,
		)

		plugin.ExitStatusCode = nagios.StateWARNINGExitCode

		return

	default:

		// success path

		log.Debug().Msg("VM Power Cycle uptime thresholds not exceeded")

		plugin.ServiceOutput = vsphere.VMPowerCycleUptimeOneLineCheckSummary(
			nagios.StateOKLabel,
			vmsFilterResults,
			uptimeSummary,
		)

		plugin.LongServiceOutput = vsphere.VMPowerCycleUptimeReport(
			c.Client,
			vmsFilterOptions,
			vmsFilterResults,
			uptimeSummary,
		)

		plugin.ExitStatusCode = nagios.StateOKExitCode

		return

	}

}
