# Copyright 2021 Adam Chalkley
#
# https://github.com/atc0005/check-vmware
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

issues:
  # equivalent CLI flag: --exclude-use-default
  #
  # see:
  #   atc0005/todo#29
  #   golangci-lint/golangci-lint#1249
  #   golangci-lint/golangci-lint#413
  exclude-use-default: false

linters:
  enable:
    - depguard
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gofmt
    - goimports
    - revive
    - gosec
    - govet

    # Deprecated linter, but still functional as of golangci-lint v1.39.0.
    # See https://github.com/atc0005/go-ci/issues/302 for more information.
    - maligned

    - misspell
    - prealloc
    - exportloopref
    - stylecheck
    - unconvert

#
# Disable fieldalignment settings until the Go team offers more control over
# the types of checks provided by the fieldalignment linter or golangci-lint
# does so.
#
# See https://github.com/atc0005/go-ci/issues/302 for more information.
#

# disable:
# - maligned

# linters-settings:
# govet:
#   enable:
#     - fieldalignment
