// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-vmware
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/atc0005/go-nagios"
	"github.com/vmware/govmomi/vim25/mo"

	"github.com/atc0005/check-vmware/internal/config"
	"github.com/atc0005/check-vmware/internal/vsphere"

	zlog "github.com/rs/zerolog/log"
)

//go:generate go-winres make --product-version=git-tag --file-version=git-tag

func main() {

	plugin := nagios.NewPlugin()

	// defer this from the start so it is the last deferred function to run
	defer plugin.ReturnCheckResults()

	// Collect last minute details just before ending plugin execution.
	defer func(plugin *nagios.Plugin) {
		// Annotate errors (if applicable) with additional context to aid in
		// troubleshooting.
		plugin.Errors = vsphere.AnnotateError(plugin.Errors...)
	}(plugin)

	// Setup configuration by parsing user-provided flags. Note plugin type so
	// that only applicable CLI flags are exposed and any plugin-specific
	// settings are applied.
	cfg, cfgErr := config.New(config.PluginType{SnapshotsAge: true})
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case cfgErr != nil:
		// We're using the standalone Err function from rs/zerolog/log as we
		// do not have a working configuration.
		zlog.Err(cfgErr).Msg("Error initializing application")
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateCRITICALLabel,
		)
		plugin.AddError(cfgErr)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	// Enable library-level logging if debug or greater logging level is
	// enabled app-wide.
	handleLibraryLogging()

	// Set context deadline equal to user-specified timeout value for plugin
	// runtime/execution.
	ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeout())
	defer cancel()

	// Record thresholds for use as Nagios "Long Service Output" content. This
	// content is shown in the detailed web UI and in notifications generated
	// by Nagios.
	plugin.CriticalThreshold = fmt.Sprintf(
		"%d day old snapshots present",
		cfg.SnapshotsAgeCritical,
	)

	plugin.WarningThreshold = fmt.Sprintf(
		"%d day old snapshots present",
		cfg.SnapshotsAgeWarning,
	)

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		plugin.BrandingCallback = config.Branding("Notification generated by ")
	}

	log := cfg.Log.With().
		Str("included_resource_pools", cfg.IncludedResourcePools.String()).
		Str("excluded_resource_pools", cfg.ExcludedResourcePools.String()).
		Str("ignored_vms", cfg.IgnoredVMs.String()).
		Int("snapshots_age_critical", cfg.SnapshotsAgeCritical).
		Int("snapshots_age_warning", cfg.SnapshotsAgeWarning).
		Logger()

	log.Debug().Msg("Logging into vSphere environment")
	c, loginErr := vsphere.Login(
		ctx, cfg.Server, cfg.Port, cfg.TrustCert,
		cfg.Username, cfg.Domain, cfg.Password,
		cfg.UserAgent(),
	)
	if loginErr != nil {
		log.Error().Err(loginErr).Msgf("error logging into %s", cfg.Server)

		plugin.AddError(loginErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error logging into %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Successfully logged into vSphere environment")

	defer func() {
		if err := c.Logout(ctx); err != nil {
			log.Error().
				Err(err).
				Msg("failed to logout")
		}
	}()

	// At this point we're logged in, ready to retrieve a list of VMs. If
	// specified, we should limit VMs based on include/exclude lists. First,
	// we'll make sure that all specified resource pools actually exist in the
	// vSphere environment.

	log.Debug().Msg("Validating resource pools")
	validateErr := vsphere.ValidateRPs(ctx, c.Client, cfg.IncludedResourcePools, cfg.ExcludedResourcePools)
	if validateErr != nil {
		log.Error().Err(validateErr).Msg("error validating include/exclude lists")

		plugin.AddError(validateErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error validating include/exclude lists",
			nagios.StateCRITICALLabel,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	log.Debug().Msg("Retrieving eligible resource pools")
	resourcePools, getRPsErr := vsphere.GetEligibleRPs(
		ctx,
		c.Client,
		cfg.IncludedResourcePools,
		cfg.ExcludedResourcePools,
		true,
	)
	if getRPsErr != nil {
		log.Error().Err(getRPsErr).Msg(
			"error retrieving list of resource pools",
		)

		plugin.AddError(getRPsErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving list of resource pools from %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	rpNames := make([]string, 0, len(resourcePools))
	for _, rp := range resourcePools {
		rpNames = append(rpNames, rp.Name)
	}

	log.Debug().
		Str("resource_pools", strings.Join(rpNames, ", ")).
		Msg("")

	log.Debug().Msg("Retrieving vms from eligible resource pools")
	rpEntityVals := make([]mo.ManagedEntity, 0, len(resourcePools))
	for i := range resourcePools {
		rpEntityVals = append(rpEntityVals, resourcePools[i].ManagedEntity)
	}
	vms, getVMsErr := vsphere.GetVMsFromContainer(ctx, c.Client, true, rpEntityVals...)
	if getVMsErr != nil {
		log.Error().Err(getVMsErr).Msg(
			"error retrieving list of VMs from resource pools list",
		)

		plugin.AddError(getVMsErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving list of VMs from resource pools list",
			nagios.StateCRITICALLabel,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	log.Debug().
		Str("vms_evaluated", strings.Join(vsphere.VMNames(vms), ", ")).
		Msg("Evaluated Virtual Machines")

	log.Debug().Msg("Drop any VMs we've been asked to exclude from checks")
	filteredVMs, numVMsExcludedByName := vsphere.ExcludeVMsByName(vms, cfg.IgnoredVMs)

	log.Debug().
		Str("vms_filtered_by_name", strings.Join(vsphere.VMNames(filteredVMs), ", ")).
		Int("vms_excluded_by_name", numVMsExcludedByName).
		Msg("VMs after name filtering")

	// NOTE: This plugin is hard-coded to evaluate powered off and powered
	// on VMs equally. I'm not sure whether ignoring powered off VMs by
	// default makes sense for this particular plugin.
	//
	// Please share your feedback here if you feel differently:
	// https://github.com/atc0005/check-vmware/discussions/177
	//
	// Please expand on some use cases for ignoring powered off VMs by default.
	//
	// 	log.Debug().Msg("Filter VMs to specified power state")
	// 	filteredVMs, numVMsExcludedByPowerState := vsphere.FilterVMsByPowerState(filteredVMs, cfg.PoweredOff)
	//
	// 	log.Debug().
	// 		Str("vms_filtered_by_power_state", strings.Join(vsphere.VMNames(filteredVMs), ", ")).
	// 		Int("vms_excluded_by_power_state", numVMsExcludedByPowerState).
	// 		Msg("VMs after power state filtering")

	log.Debug().Msg("Filter VMs to those with snapshots")
	vmsWithSnapshots, numVMsExcludedBySnapshots := vsphere.FilterVMsWithSnapshots(filteredVMs)

	log.Debug().
		Str("vms_filtered_by_snapshot_state", strings.Join(vsphere.VMNames(vmsWithSnapshots), ", ")).
		Int("vms_excluded_by_snapshot_state", numVMsExcludedBySnapshots).
		Msg("VMs after snapshot filtering")

	log.Debug().Msg("Build snapshot sets for bulk processing")
	snapshotSets := make(vsphere.SnapshotSummarySets, 0, len(vmsWithSnapshots))

	snapshotThresholds := vsphere.SnapshotThresholds{
		AgeCritical: cfg.SnapshotsAgeCritical,
		AgeWarning:  cfg.SnapshotsAgeWarning,
	}

	for _, vm := range vmsWithSnapshots {

		log.Debug().Str("vm", vm.Name).Msg("Evaluating snapshots for VM")

		snapshotSets = append(
			snapshotSets,
			vsphere.NewSnapshotSummarySet(
				vm,
				snapshotThresholds,
			),
		)
	}

	log.Debug().Msg("Compiling Performance Data details")

	numVMsWithCriticalSnapshots, numCriticalSnapshots := snapshotSets.AgeCriticalSnapshots()
	numVMsWithWarningSnapshots, numWarningSnapshots := snapshotSets.AgeWarningSnapshots()
	numSnapshots := snapshotSets.Snapshots()

	pd := []nagios.PerformanceData{
		// The `time` (runtime) metric is appended at plugin exit, so do not
		// duplicate it here.
		{
			Label: "vms",
			Value: fmt.Sprintf("%d", len(vms)),
		},
		{
			Label: "vms_with_critical_snapshots",
			Value: fmt.Sprintf("%d", numVMsWithCriticalSnapshots),
		},
		{
			Label: "vms_with_warning_snapshots",
			Value: fmt.Sprintf("%d", numVMsWithWarningSnapshots),
		},
		{
			Label: "snapshots",
			Value: fmt.Sprintf("%d", numSnapshots),
		},
		{
			Label: "critical_snapshots",
			Value: fmt.Sprintf("%d", numCriticalSnapshots),
		},
		{
			Label: "warning_snapshots",
			Value: fmt.Sprintf("%d", numWarningSnapshots),
		},
		{
			Label: "resource_pools_excluded",
			Value: fmt.Sprintf("%d", len(cfg.ExcludedResourcePools)),
		},
		{
			Label: "resource_pools_included",
			Value: fmt.Sprintf("%d", len(cfg.IncludedResourcePools)),
		},
		{
			Label: "resource_pools_evaluated",
			Value: fmt.Sprintf("%d", len(resourcePools)),
		},
	}

	// Update logger with new performance data related fields
	log = log.With().
		Int("vms_total", len(vms)).
		Int("snapshots_total", numSnapshots).
		Int("vms_filtered", len(filteredVMs)).
		Int("vms_excluded_by_name", numVMsExcludedByName).
		Int("num_vms_with_critical_snapshots", numVMsWithCriticalSnapshots).
		Int("num_snapshots_age_critical", numCriticalSnapshots).
		Int("num_vms_with_warning_snapshots", numVMsWithWarningSnapshots).
		Int("num_snapshots_age_warning", numWarningSnapshots).
		Int("resource_pools_evaluated", len(resourcePools)).
		Logger()

	switch {

	case snapshotSets.IsAgeCriticalState():

		log.Error().
			Msg("Snapshot sets contain a snapshot which exceeds specified age in days")

		plugin.AddError(vsphere.ErrSnapshotAgeThresholdCrossed)

		plugin.ServiceOutput = vsphere.SnapshotsAgeOneLineCheckSummary(
			nagios.StateCRITICALLabel,
			snapshotSets,
			snapshotThresholds,
			filteredVMs,
			resourcePools,
		)

		plugin.LongServiceOutput = vsphere.SnapshotsAgeReport(
			c.Client,
			snapshotSets,
			snapshotThresholds,
			vms,
			filteredVMs,
			vmsWithSnapshots,
			cfg.IgnoredVMs,
			cfg.PoweredOff,
			cfg.IncludedResourcePools,
			cfg.ExcludedResourcePools,
			resourcePools,
		)

		if err := plugin.AddPerfData(false, pd...); err != nil {
			log.Error().
				Err(err).
				Msg("failed to add performance data")
		}

		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return

	case snapshotSets.IsAgeWarningState():

		log.Error().
			Msg("Snapshot sets contain one or more snapshots which exceed specified age in days")

		plugin.AddError(vsphere.ErrSnapshotAgeThresholdCrossed)

		plugin.ServiceOutput = vsphere.SnapshotsAgeOneLineCheckSummary(
			nagios.StateWARNINGLabel,
			snapshotSets,
			snapshotThresholds,
			filteredVMs,
			resourcePools,
		)

		plugin.LongServiceOutput = vsphere.SnapshotsAgeReport(
			c.Client,
			snapshotSets,
			snapshotThresholds,
			vms,
			filteredVMs,
			vmsWithSnapshots,
			cfg.IgnoredVMs,
			cfg.PoweredOff,
			cfg.IncludedResourcePools,
			cfg.ExcludedResourcePools,
			resourcePools,
		)

		if err := plugin.AddPerfData(false, pd...); err != nil {
			log.Error().
				Err(err).
				Msg("failed to add performance data")
		}

		plugin.ExitStatusCode = nagios.StateWARNINGExitCode

		return

	default:

		log.Debug().Msg("No snapshots found which exceed specified age in days")

		plugin.ServiceOutput = vsphere.SnapshotsAgeOneLineCheckSummary(
			nagios.StateOKLabel,
			snapshotSets,
			snapshotThresholds,
			filteredVMs,
			resourcePools,
		)

		plugin.LongServiceOutput = vsphere.SnapshotsAgeReport(
			c.Client,
			snapshotSets,
			snapshotThresholds,
			vms,
			filteredVMs,
			vmsWithSnapshots,
			cfg.IgnoredVMs,
			cfg.PoweredOff,
			cfg.IncludedResourcePools,
			cfg.ExcludedResourcePools,
			resourcePools,
		)

		if err := plugin.AddPerfData(false, pd...); err != nil {
			log.Error().
				Err(err).
				Msg("failed to add performance data")
		}

		plugin.ExitStatusCode = nagios.StateOKExitCode

		return

	}

}
