// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-vmware
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"context"
	"errors"
	"fmt"

	"github.com/atc0005/go-nagios"

	"github.com/atc0005/check-vmware/internal/config"
	"github.com/atc0005/check-vmware/internal/vsphere"

	zlog "github.com/rs/zerolog/log"
)

func main() {

	// Set initial "state" as valid, adjust as we go.
	var nagiosExitState = nagios.ExitState{
		LastError:      nil,
		ExitStatusCode: nagios.StateOKExitCode,
	}

	// defer this from the start so it is the last deferred function to run
	defer nagiosExitState.ReturnCheckResults()

	// Disable library debug logging output by default
	// vsphere.EnableLogging()
	vsphere.DisableLogging()

	// Setup configuration by parsing user-provided flags. Note plugin type so
	// that only applicable CLI flags are exposed and any plugin-specific
	// settings are applied.
	cfg, cfgErr := config.New(config.PluginType{HostSystemCPU: true})
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case cfgErr != nil:
		// We're using the standalone Err function from rs/zerolog/log as we
		// do not have a working configuration.
		zlog.Err(cfgErr).Msg("Error initializing application")
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateCRITICALLabel,
		)
		nagiosExitState.LastError = cfgErr
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	// Enable library-level logging if debug logging level is enabled app-wide
	if cfg.LoggingLevel == config.LogLevelDebug {
		vsphere.EnableLogging()
	}

	ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeout())
	defer cancel()

	// Record thresholds for use as Nagios "Long Service Output" content. This
	// content is shown in the detailed web UI and in notifications generated
	// by Nagios.
	nagiosExitState.CriticalThreshold = fmt.Sprintf(
		"%d%% CPU usage",
		cfg.HostSystemCPUUseCritical,
	)

	nagiosExitState.WarningThreshold = fmt.Sprintf(
		"%d%% CPU usage",
		cfg.HostSystemCPUUseWarning,
	)

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		nagiosExitState.BrandingCallback = config.Branding("Notification generated by ")
	}

	dcName := cfg.DatacenterName
	if dcName == "" {
		dcName = "not provided"
	}

	log := cfg.Log.With().
		Str("host_system_name", cfg.HostSystemName).
		Str("datacenter_name", dcName).
		Int("host_system_cpu_critical_usage", cfg.HostSystemCPUUseCritical).
		Int("host_system_cpu_warning_usage", cfg.HostSystemCPUUseWarning).
		Logger()

	log.Debug().Msg("Logging into vSphere environment")
	c, loginErr := vsphere.Login(
		ctx, cfg.Server, cfg.Port, cfg.TrustCert,
		cfg.Username, cfg.Domain, cfg.Password,
	)
	if loginErr != nil {
		log.Error().Err(loginErr).Msgf("error logging into %s", cfg.Server)

		nagiosExitState.LastError = loginErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error logging into %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Successfully logged into vSphere environment")

	defer func() {
		if err := c.Logout(ctx); err != nil {
			log.Error().
				Err(err).
				Msg("failed to logout")
		}
	}()

	// At this point we're logged in, ready to retrieve the requested
	// HostSystem.

	log.Debug().Msg("Retrieving host by name")
	hostSystem, hsFetchErr := vsphere.GetHostSystemByName(
		ctx,
		c.Client,
		cfg.HostSystemName,
		cfg.DatacenterName,
		true,
	)
	if hsFetchErr != nil {
		log.Error().Err(hsFetchErr).Msg(
			"error retrieving requested host",
		)

		nagiosExitState.LastError = hsFetchErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving host %q",
			nagios.StateCRITICALLabel,
			cfg.HostSystemName,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Successfully retrieved host by name")

	log.Debug().Msg("Generating host CPU usage summary")
	hsUsage := vsphere.NewHostSystemCPUUsageSummary(
		hostSystem,
		cfg.HostSystemCPUUseCritical,
		cfg.HostSystemCPUUseWarning,
	)

	log.Debug().
		Str("host_system_name", hostSystem.Name).
		Float64("host_system_cpu_used_percentage", hsUsage.CPUUsedPercent).
		Float64("host_system_cpu_remaining_percentage", hsUsage.CPURemainingPercent).
		Str("host_system_cpu_total", vsphere.CPUSpeed(hsUsage.CPUTotal).String()).
		Str("host_system_cpu_used", vsphere.CPUSpeed(hsUsage.CPUUsed).String()).
		Str("host_system_cpu_remaining", vsphere.CPUSpeed(hsUsage.CPURemaining).String()).
		Int("host_system_critical_threshold", hsUsage.CriticalThreshold).
		Int("host_system_warning_threshold", hsUsage.WarningThreshold).
		Msg("HostSystem CPU usage summary")

	log.Debug().Msg("Retrieving VMs for host")
	hsVMs, hsVMsFetchErr := vsphere.GetVMsFromContainer(ctx, c.Client, true, hostSystem.ManagedEntity)
	if hsVMsFetchErr != nil {
		log.Error().Err(hsVMsFetchErr).Msg(
			"error retrieving VirtualMachines from host",
		)

		nagiosExitState.LastError = hsVMsFetchErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving VirtualMachines from host %q",
			nagios.StateCRITICALLabel,
			cfg.HostSystemName,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	log.Debug().Msg("Evaluating host CPU usage state")
	switch {
	case hsUsage.IsCriticalState():

		log.Error().
			Str("host_name", hostSystem.Name).
			Float64("host_system_usage_used_percentage", hsUsage.CPUUsedPercent).
			Float64("host_system_usage_remaining_percentage", hsUsage.CPURemainingPercent).
			Str("host_system_cpu_remaining", vsphere.CPUSpeed(hsUsage.CPURemaining).String()).
			Msg("host CPU usage threshold crossed")

		nagiosExitState.LastError = vsphere.ErrHostSystemCPUUsageThresholdCrossed

		nagiosExitState.ServiceOutput = vsphere.HostSystemCPUUsageOneLineCheckSummary(
			nagios.StateCRITICALLabel,
			hsVMs,
			hsUsage,
		)

		nagiosExitState.LongServiceOutput = vsphere.HostSystemCPUUsageReport(
			c.Client,
			hsVMs,
			hsUsage,
		)

		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return

	case hsUsage.IsWarningState():

		log.Error().
			Str("host_name", hostSystem.Name).
			Float64("host_cpu_usage_used_percentage", hsUsage.CPUUsedPercent).
			Float64("host_cpu_usage_remaining_percentage", hsUsage.CPURemainingPercent).
			Str("host_cpu_remaining", vsphere.CPUSpeed(hsUsage.CPURemaining).String()).
			Msg("host CPU usage threshold crossed")

		nagiosExitState.LastError = vsphere.ErrHostSystemCPUUsageThresholdCrossed

		nagiosExitState.ServiceOutput = vsphere.HostSystemCPUUsageOneLineCheckSummary(
			nagios.StateWARNINGLabel,
			hsVMs,
			hsUsage,
		)

		nagiosExitState.LongServiceOutput = vsphere.HostSystemCPUUsageReport(
			c.Client,
			hsVMs,
			hsUsage,
		)

		nagiosExitState.ExitStatusCode = nagios.StateWARNINGExitCode

		return

	default:

		log.Debug().Msg("Host CPU usage thresholds not exceeded")

		nagiosExitState.LastError = nil

		nagiosExitState.ServiceOutput = vsphere.HostSystemCPUUsageOneLineCheckSummary(
			nagios.StateOKLabel,
			hsVMs,
			hsUsage,
		)

		nagiosExitState.LongServiceOutput = vsphere.HostSystemCPUUsageReport(
			c.Client,
			hsVMs,
			hsUsage,
		)

		nagiosExitState.ExitStatusCode = nagios.StateOKExitCode

		return

	}

}
