// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-vmware
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/atc0005/go-nagios"

	"github.com/atc0005/check-vmware/internal/config"
	"github.com/atc0005/check-vmware/internal/vsphere"

	zlog "github.com/rs/zerolog/log"
)

//go:generate go-winres make --product-version=git-tag --file-version=git-tag

func main() {

	plugin := nagios.NewPlugin()

	// defer this from the start so it is the last deferred function to run
	defer plugin.ReturnCheckResults()

	// Annotate all errors (if any) with remediation advice just before ending
	// plugin execution.
	defer vsphere.AnnotateError(plugin)

	// Setup configuration by parsing user-provided flags. Note plugin type so
	// that only applicable CLI flags are exposed and any plugin-specific
	// settings are applied.
	cfg, cfgErr := config.New(config.PluginType{Tools: true})
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case cfgErr != nil:
		// We're using the standalone Err function from rs/zerolog/log as we
		// do not have a working configuration.
		zlog.Err(cfgErr).Msg("Error initializing application")
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateUNKNOWNLabel,
		)
		plugin.AddError(cfgErr)
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode

		return
	}

	// Enable library-level logging if debug or greater logging level is
	// enabled app-wide.
	handleLibraryLogging()

	// Set context deadline equal to user-specified timeout value for plugin
	// runtime/execution.
	ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeout())
	defer cancel()

	// Record thresholds for use as Nagios "Long Service Output" content. This
	// content is shown in the detailed web UI and in notifications generated
	// by Nagios.
	plugin.CriticalThreshold =
		"VMware Tools not running, not installed, unsupported or blacklisted version."

	plugin.WarningThreshold =
		"Outdated VMware Tools installation."

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		plugin.BrandingCallback = config.Branding("Notification generated by ")
	}

	log := cfg.Log.With().
		Str("included_resource_pools", cfg.IncludedResourcePools.String()).
		Str("excluded_resource_pools", cfg.ExcludedResourcePools.String()).
		Int("num_excluded_resource_pools", len(cfg.ExcludedResourcePools)).
		Int("num_included_resource_pools", len(cfg.IncludedResourcePools)).
		Str("ignored_vms", cfg.IgnoredVMs.String()).
		Bool("eval_powered_off", cfg.PoweredOff).
		Logger()

	log.Debug().Msg("Logging into vSphere environment")
	c, loginErr := vsphere.Login(
		ctx, cfg.Server, cfg.Port, cfg.TrustCert,
		cfg.Username, cfg.Domain, cfg.Password,
		cfg.UserAgent(),
	)
	if loginErr != nil {
		log.Error().Err(loginErr).Msgf("error logging into %s", cfg.Server)

		plugin.AddError(loginErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error logging into %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Successfully logged into vSphere environment")

	defer func() {
		if err := c.Logout(ctx); err != nil {
			log.Error().
				Err(err).
				Msg("failed to logout")
		}
	}()

	log.Debug().Msg("Filtering vms")
	vmsFilterOptions := vsphere.VMsFilterOptions{
		ResourcePoolsIncluded:       cfg.IncludedResourcePools,
		ResourcePoolsExcluded:       cfg.ExcludedResourcePools,
		FoldersIncluded:             cfg.IncludedFolders,
		FoldersExcluded:             cfg.ExcludedFolders,
		VirtualMachineNamesExcluded: cfg.IgnoredVMs,
		IncludePoweredOff:           cfg.PoweredOff,
	}
	vmsFilterResults, vmsFilterErr := vsphere.FilterVMs(
		ctx,
		c.Client,
		vmsFilterOptions,
	)
	if vmsFilterErr != nil {
		log.Error().Err(vmsFilterErr).Msg(
			"error filtering VMs",
		)

		plugin.AddError(vmsFilterErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error filtering VMs",
			nagios.StateCRITICALLabel,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Finished filtering vms")

	log.Debug().Msg("Filter VMs to those with VMware Tools issues")
	// Create a new collection of VMs with just those found to have Tools
	// issues.
	vmsWithIssues, numVMsWithoutToolsIssues := vsphere.FilterVMsWithToolsIssues(vmsFilterResults.VMsAfterFiltering(), cfg.PoweredOff)
	numVMsWithToolsIssues := len(vmsWithIssues)

	log.Debug().
		Str("vms_filtered_by_tools_issues", strings.Join(vsphere.VMNames(vmsWithIssues), ", ")).
		Int("vms_with_tools_issues", numVMsWithToolsIssues).
		Int("vms_excluded_by_tools_issues", numVMsWithoutToolsIssues).
		Msg("VMs after tools issues filtering")

	log.Debug().Msg("Compiling Performance Data details")

	pd := append(
		vsphere.VMFilterResultsPerfData(vmsFilterResults),
		[]nagios.PerformanceData{
			// The `time` (runtime) metric is appended at plugin exit, so do not
			// duplicate it here.
			{
				Label: "vms_with_tools_issues",
				Value: fmt.Sprintf("%d", numVMsWithToolsIssues),
			},
			{
				Label: "vms_without_tools_issues",
				Value: fmt.Sprintf("%d", numVMsWithoutToolsIssues),
			},
		}...,
	)

	if err := plugin.AddPerfData(false, pd...); err != nil {
		log.Error().
			Err(err).
			Msg("failed to add performance data")

		// Surface the error in plugin output.
		plugin.AddError(err)

		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Failed to process performance data metrics",
			nagios.StateUNKNOWNLabel,
		)

		return
	}

	// Update logger with new performance data related fields
	log = log.With().
		Int("resource_pools_evaluated", vmsFilterResults.NumRPsAfterFiltering()).
		Int("vms_total", vmsFilterResults.NumVMsAll()).
		Int("vms_after_filtering", vmsFilterResults.NumVMsAfterFiltering()).
		Int("vms_excluded_by_name", vmsFilterResults.NumVMsExcludedByName()).
		Int("vms_excluded_by_power_state", vmsFilterResults.NumVMsExcludedByPowerState()).
		Int("vms_with_tools_issues", numVMsWithToolsIssues).
		Int("vms_without_tools_issues", numVMsWithoutToolsIssues).
		Logger()

	if len(vmsWithIssues) > 0 {

		log.Error().Msg("issues with VMware Tools found")

		serviceState := vsphere.GetVMToolsStatusSummary(vmsWithIssues)

		plugin.AddError(fmt.Errorf(
			"%d of %d VMs with VMware Tools issues",
			len(vmsWithIssues),
			vmsFilterResults.NumVMsAfterFiltering(),
		))

		plugin.ServiceOutput = vsphere.VMToolsOneLineCheckSummary(
			serviceState.Label,
			vmsFilterResults,
			vmsWithIssues,
		)

		plugin.LongServiceOutput = vsphere.VMToolsReport(
			c.Client,
			vmsFilterOptions,
			vmsFilterResults,
			vmsWithIssues,
		)

		plugin.ExitStatusCode = serviceState.ExitCode

		return

	}

	// success if we made it here

	log.Debug().
		Int("vms_total", vmsFilterResults.NumVMsAll()).
		Int("vms_with_issues", numVMsWithToolsIssues).
		Int("vms_without_issues", numVMsWithoutToolsIssues).
		Msg("No problems with VMware Tools found")

	plugin.ServiceOutput = vsphere.VMToolsOneLineCheckSummary(
		nagios.StateOKLabel,
		vmsFilterResults,
		vmsWithIssues,
	)

	plugin.LongServiceOutput = vsphere.VMToolsReport(
		c.Client,
		vmsFilterOptions,
		vmsFilterResults,
		vmsWithIssues,
	)

	plugin.ExitStatusCode = nagios.StateOKExitCode

}
