// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-vmware
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/atc0005/go-nagios"

	"github.com/atc0005/check-vmware/internal/config"
	"github.com/atc0005/check-vmware/internal/vsphere"

	zlog "github.com/rs/zerolog/log"
)

//go:generate go-winres make --product-version=git-tag --file-version=git-tag

func main() {

	plugin := nagios.NewPlugin()

	// defer this from the start so it is the last deferred function to run
	defer plugin.ReturnCheckResults()

	// Annotate all errors (if any) with remediation advice just before ending
	// plugin execution.
	defer vsphere.AnnotateError(plugin)

	// Setup configuration by parsing user-provided flags. Note plugin type so
	// that only applicable CLI flags are exposed and any plugin-specific
	// settings are applied.
	cfg, cfgErr := config.New(config.PluginType{VirtualHardwareVersion: true})
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case cfgErr != nil:
		// We're using the standalone Err function from rs/zerolog/log as we
		// do not have a working configuration.
		zlog.Err(cfgErr).Msg("Error initializing application")
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateUNKNOWNLabel,
		)
		plugin.AddError(cfgErr)
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode

		return
	}

	// Enable library-level logging if debug or greater logging level is
	// enabled app-wide.
	handleLibraryLogging()

	// Set context deadline equal to user-specified timeout value for plugin
	// runtime/execution.
	ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeout())
	defer cancel()

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		plugin.BrandingCallback = config.Branding("Notification generated by ")
	}

	log := cfg.Log.With().
		Str("included_resource_pools", cfg.IncludedResourcePools.String()).
		Str("excluded_resource_pools", cfg.ExcludedResourcePools.String()).
		Str("ignored_vms", cfg.IgnoredVMs.String()).
		Bool("eval_powered_off", cfg.PoweredOff).
		Logger()

	log.Debug().Msg("Logging into vSphere environment")
	c, loginErr := vsphere.Login(
		ctx, cfg.Server, cfg.Port, cfg.TrustCert,
		cfg.Username, cfg.Domain, cfg.Password,
		cfg.UserAgent(),
	)
	if loginErr != nil {
		log.Error().Err(loginErr).Msgf("error logging into %s", cfg.Server)

		plugin.AddError(loginErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error logging into %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Successfully logged into vSphere environment")

	defer func() {
		if err := c.Logout(ctx); err != nil {
			log.Error().
				Err(err).
				Msg("failed to logout")
		}
	}()

	log.Debug().Msg("Performing initial filtering of vms")
	vmsFilterOptions := vsphere.VMsFilterOptions{
		ResourcePoolsIncluded:       cfg.IncludedResourcePools,
		ResourcePoolsExcluded:       cfg.ExcludedResourcePools,
		FoldersIncluded:             cfg.IncludedFolders,
		FoldersExcluded:             cfg.ExcludedFolders,
		VirtualMachineNamesExcluded: cfg.IgnoredVMs,
		IncludePoweredOff:           cfg.PoweredOff,
	}
	vmsFilterResults, vmsFilterErr := vsphere.FilterVMs(
		ctx,
		c.Client,
		vmsFilterOptions,
	)
	if vmsFilterErr != nil {
		log.Error().Err(vmsFilterErr).Msg(
			"error filtering VMs",
		)

		plugin.AddError(vmsFilterErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error filtering VMs",
			nagios.StateCRITICALLabel,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Finished initial filtering of vms")

	// here we diverge from other plugins

	hardwareVersionsIdx, hwIdxErr := vsphere.NewHardwareVersionsIndex(vmsFilterResults.VMsAfterFiltering())
	if hwIdxErr != nil {
		log.Error().Err(hwIdxErr).Msg("error creating virtual hardware index")

		plugin.AddError(hwIdxErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error creating index of virtual hardware versions",
			nagios.StateCRITICALLabel,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	defaultHardwareVersion, getDefVerErr := vsphere.DefaultHardwareVersion(
		ctx,
		c.Client,
		cfg.HostSystemName,
		cfg.ClusterName,
		cfg.DatacenterName,
		hardwareVersionsIdx,
	)
	if getDefVerErr != nil {
		log.Error().Err(getDefVerErr).Msg(
			"error retrieving default hardware version",
		)

		plugin.AddError(getDefVerErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving default hardware version",
			nagios.StateCRITICALLabel,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	log.Debug().
		Int("default_hardware_version", defaultHardwareVersion.VersionNumber()).
		Int("vms_with_default_hardware_version", defaultHardwareVersion.Count()).
		Msg("")

	log.Debug().Msg("Compiling Performance Data details")

	pd := append(
		vsphere.VMFilterResultsPerfData(vmsFilterResults),
		[]nagios.PerformanceData{
			// The `time` (runtime) metric is appended at plugin exit, so do not
			// duplicate it here.
			{
				Label: "hardware_versions_unique",
				Value: fmt.Sprintf("%d", hardwareVersionsIdx.Count()),
			},
			{
				Label: "hardware_versions_newest",
				Value: fmt.Sprintf("%d", hardwareVersionsIdx.Newest().Count()),
			},
			{
				Label: "hardware_versions_default",
				Value: fmt.Sprintf("%d", defaultHardwareVersion.Count()),
			},
			{
				Label: "hardware_versions_oldest",
				Value: fmt.Sprintf("%d", hardwareVersionsIdx.Oldest().Count()),
			},
		}...,
	)

	if err := plugin.AddPerfData(false, pd...); err != nil {
		log.Error().
			Err(err).
			Msg("failed to add performance data")

		// Surface the error in plugin output.
		plugin.AddError(err)

		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Failed to process performance data metrics",
			nagios.StateUNKNOWNLabel,
		)

		return
	}

	// Update logger with new performance data related fields
	log = log.With().
		Int("resource_pools_evaluated", vmsFilterResults.NumRPsAfterFiltering()).
		Int("vms_total", vmsFilterResults.NumVMsAll()).
		Int("vms_after_filtering", vmsFilterResults.NumVMsAfterFiltering()).
		Int("vms_excluded_by_name", vmsFilterResults.NumVMsExcludedByName()).
		Int("vms_excluded_by_power_state", vmsFilterResults.NumVMsExcludedByPowerState()).
		Int("hardware_versions_unique", hardwareVersionsIdx.Count()).
		Int("hardware_versions_newest", hardwareVersionsIdx.Newest().Count()).
		Int("hardware_versions_oldest", hardwareVersionsIdx.Oldest().Count()).
		Int("default_hardware_version", defaultHardwareVersion.VersionNumber()).
		Str("hardware_newest", hardwareVersionsIdx.Newest().String()).
		Str("hardware_oldest", hardwareVersionsIdx.Oldest().String()).
		Str("outdated_hardware_list", strings.Join(
			hardwareVersionsIdx.Outdated().VersionNames(), ", ")).
		Logger()

	if cfg.VirtualHardwareApplyHomogeneousVersionCheck() {

		// Record thresholds for use as Nagios "Long Service Output" content. This
		// content is shown in the detailed web UI and in notifications generated
		// by Nagios.
		plugin.CriticalThreshold = config.ThresholdNotUsed
		plugin.WarningThreshold = "Non-homogenous hardware versions."

		switch {

		// There are at least two hardware versions present instead of a
		// uniform version across all VirtualMachines.
		case hardwareVersionsIdx.Count() > 1:

			log.Error().Msg("Virtual Hardware versions inconsistency detected")

			plugin.AddError(vsphere.ErrVirtualHardwareOutdatedVersionsFound)

			plugin.ServiceOutput = vsphere.VirtualHardwareOneLineCheckSummary(
				nagios.StateWARNINGLabel,
				vmsFilterResults,
				hardwareVersionsIdx.Newest().VersionNumber(),
			)

			plugin.LongServiceOutput = vsphere.VirtualHardwareReport(
				c.Client,
				vmsFilterOptions,
				vmsFilterResults,
				hardwareVersionsIdx,
				hardwareVersionsIdx.Newest().VersionNumber(),
				defaultHardwareVersion,
			)

			plugin.ExitStatusCode = nagios.StateWARNINGExitCode

			return

		default:

			// same hardware version

			log.Debug().Msg("Homogenous hardware versions found")

			plugin.ServiceOutput = vsphere.VirtualHardwareOneLineCheckSummary(
				nagios.StateOKLabel,
				vmsFilterResults,
				hardwareVersionsIdx.Newest().VersionNumber(),
			)

			plugin.LongServiceOutput = vsphere.VirtualHardwareReport(
				c.Client,
				vmsFilterOptions,
				vmsFilterResults,
				hardwareVersionsIdx,
				hardwareVersionsIdx.Newest().VersionNumber(),
				defaultHardwareVersion,
			)

			plugin.ExitStatusCode = nagios.StateOKExitCode

			return

		}

	}

	if cfg.VirtualHardwareApplyMinVersionCheck() {

		// Record thresholds for use as Nagios "Long Service Output" content. This
		// content is shown in the detailed web UI and in notifications generated
		// by Nagios.
		plugin.CriticalThreshold = fmt.Sprintf(
			"Hardware versions older than the minimum (%d) present.",
			cfg.VirtualHardwareMinimumVersion,
		)
		plugin.WarningThreshold = config.ThresholdNotUsed

		hardwareVersions := hardwareVersionsIdx.Versions()

		switch {
		case !hardwareVersions.MeetsMinVersion(cfg.VirtualHardwareMinimumVersion):

			log.Error().
				Msg("Virtual Hardware versions older than the specified minimum version detected")

			plugin.AddError(vsphere.ErrVirtualHardwareOutdatedVersionsFound)

			plugin.ServiceOutput = vsphere.VirtualHardwareOneLineCheckSummary(
				nagios.StateCRITICALLabel,
				vmsFilterResults,
				cfg.VirtualHardwareMinimumVersion,
			)

			plugin.LongServiceOutput = vsphere.VirtualHardwareReport(
				c.Client,
				vmsFilterOptions,
				vmsFilterResults,
				hardwareVersionsIdx,
				cfg.VirtualHardwareMinimumVersion,
				defaultHardwareVersion,
			)

			plugin.ExitStatusCode = nagios.StateCRITICALExitCode

			return

		default:

			log.Debug().Msg("Minimum hardware version met")

			plugin.ServiceOutput = vsphere.VirtualHardwareOneLineCheckSummary(
				nagios.StateOKLabel,
				vmsFilterResults,
				cfg.VirtualHardwareMinimumVersion,
			)

			plugin.LongServiceOutput = vsphere.VirtualHardwareReport(
				c.Client,
				vmsFilterOptions,
				vmsFilterResults,
				hardwareVersionsIdx,
				cfg.VirtualHardwareMinimumVersion,
				defaultHardwareVersion,
			)

			plugin.ExitStatusCode = nagios.StateOKExitCode

			return
		}

	}

	if cfg.VirtualHardwareApplyDefaultIsMinVersionCheck() {

		// Record thresholds for use as Nagios "Long Service Output" content. This
		// content is shown in the detailed web UI and in notifications generated
		// by Nagios.
		plugin.CriticalThreshold = config.ThresholdNotUsed

		plugin.WarningThreshold = fmt.Sprintf(
			"Hardware versions older than the default host or cluster (%d) present.",
			defaultHardwareVersion.VersionNumber(),
		)

		hardwareVersions := hardwareVersionsIdx.Versions()

		switch {
		case !hardwareVersions.MeetsMinVersion(defaultHardwareVersion.VersionNumber()):

			log.Error().
				Msg("Virtual Hardware versions older than the host or cluster default version detected")

			plugin.AddError(vsphere.ErrVirtualHardwareOutdatedVersionsFound)

			plugin.ServiceOutput = vsphere.VirtualHardwareOneLineCheckSummary(
				nagios.StateWARNINGLabel,
				vmsFilterResults,
				defaultHardwareVersion.VersionNumber(),
			)

			plugin.LongServiceOutput = vsphere.VirtualHardwareReport(
				c.Client,
				vmsFilterOptions,
				vmsFilterResults,
				hardwareVersionsIdx,
				defaultHardwareVersion.VersionNumber(),
				defaultHardwareVersion,
			)

			plugin.ExitStatusCode = nagios.StateWARNINGExitCode

			return

		default:

			log.Debug().Msg("Default hardware version met")

			plugin.ServiceOutput = vsphere.VirtualHardwareOneLineCheckSummary(
				nagios.StateOKLabel,
				vmsFilterResults,
				defaultHardwareVersion.VersionNumber(),
			)

			plugin.LongServiceOutput = vsphere.VirtualHardwareReport(
				c.Client,
				vmsFilterOptions,
				vmsFilterResults,
				hardwareVersionsIdx,
				defaultHardwareVersion.VersionNumber(),
				defaultHardwareVersion,
			)

			plugin.ExitStatusCode = nagios.StateOKExitCode

			return
		}

	}

	if cfg.VirtualHardwareApplyOutdatedByVersionCheck() {

		// Record thresholds for use as Nagios "Long Service Output" content. This
		// content is shown in the detailed web UI and in notifications generated
		// by Nagios.
		plugin.CriticalThreshold = fmt.Sprintf(
			"Hardware versions outdated by more than %d versions present.",
			cfg.VirtualHardwareOutdatedByCritical,
		)
		plugin.WarningThreshold = fmt.Sprintf(
			"Hardware versions outdated by more than %d versions present.",
			cfg.VirtualHardwareOutdatedByWarning,
		)

		hardwareVersions := hardwareVersionsIdx.Versions()
		latestHWVerNum := hardwareVersionsIdx.Newest().VersionNumber()
		criticalThresholdVerNum := latestHWVerNum - cfg.VirtualHardwareOutdatedByCritical
		warningThresholdVerNum := latestHWVerNum - cfg.VirtualHardwareOutdatedByWarning

		switch {
		case !hardwareVersions.MeetsMinVersion(criticalThresholdVerNum):

			log.Error().
				Msg("Virtual Hardware versions older than the specified minimum version detected")

			plugin.AddError(vsphere.ErrVirtualHardwareOutdatedVersionsFound)

			plugin.ServiceOutput = vsphere.VirtualHardwareOneLineCheckSummary(
				nagios.StateCRITICALLabel,
				vmsFilterResults,
				criticalThresholdVerNum,
			)

			plugin.LongServiceOutput = vsphere.VirtualHardwareReport(
				c.Client,
				vmsFilterOptions,
				vmsFilterResults,
				hardwareVersionsIdx,
				criticalThresholdVerNum,
				defaultHardwareVersion,
			)

			plugin.ExitStatusCode = nagios.StateCRITICALExitCode

			return

		case !hardwareVersions.MeetsMinVersion(warningThresholdVerNum):

			log.Error().
				Msg("Virtual Hardware versions older than the specified minimum version detected")

			plugin.AddError(vsphere.ErrVirtualHardwareOutdatedVersionsFound)

			plugin.ServiceOutput = vsphere.VirtualHardwareOneLineCheckSummary(
				nagios.StateWARNINGLabel,
				vmsFilterResults,
				warningThresholdVerNum,
			)

			plugin.LongServiceOutput = vsphere.VirtualHardwareReport(
				c.Client,
				vmsFilterOptions,
				vmsFilterResults,
				hardwareVersionsIdx,
				warningThresholdVerNum,
				defaultHardwareVersion,
			)

			plugin.ExitStatusCode = nagios.StateWARNINGExitCode

			return

		default:

			log.Debug().
				Msg("Virtual Hardware versions meet the specified minimum version")

			plugin.ServiceOutput = vsphere.VirtualHardwareOneLineCheckSummary(
				nagios.StateOKLabel,
				vmsFilterResults,
				warningThresholdVerNum,
			)

			plugin.LongServiceOutput = vsphere.VirtualHardwareReport(
				c.Client,
				vmsFilterOptions,
				vmsFilterResults,
				hardwareVersionsIdx,
				warningThresholdVerNum,
				defaultHardwareVersion,
			)

			plugin.ExitStatusCode = nagios.StateOKExitCode

			return
		}

	}

}
