// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-vmware
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/atc0005/go-nagios"
	"github.com/vmware/govmomi/units"
	"github.com/vmware/govmomi/vim25/mo"

	"github.com/atc0005/check-vmware/internal/config"
	"github.com/atc0005/check-vmware/internal/vsphere"

	zlog "github.com/rs/zerolog/log"
)

func main() {

	// Start the timer. We'll use this to emit the plugin runtime as a
	// performance data metric.
	pluginStart := time.Now()

	// Set initial "state" as valid, adjust as we go.
	var nagiosExitState = nagios.ExitState{
		LastError:      nil,
		ExitStatusCode: nagios.StateOKExitCode,
	}

	// defer this from the start so it is the last deferred function to run
	defer nagiosExitState.ReturnCheckResults()

	// Collect last minute details just before ending plugin execution.
	defer func(exitState *nagios.ExitState, start time.Time) {

		// Record plugin runtime, emit this metric regardless of exit
		// point/cause.
		runtimeMetric := nagios.PerformanceData{
			Label: "time",
			Value: fmt.Sprintf("%dms", time.Since(start).Milliseconds()),
		}
		if err := exitState.AddPerfData(false, runtimeMetric); err != nil {
			zlog.Error().
				Err(err).
				Msg("failed to add time (runtime) performance data metric")
		}

		// Annotate errors (if applicable) with additional context to aid in
		// troubleshooting.
		nagiosExitState.LastError = vsphere.AnnotateError(nagiosExitState.LastError)
	}(&nagiosExitState, pluginStart)

	// Disable library debug logging output by default
	// vsphere.EnableLogging()
	vsphere.DisableLogging()

	// Setup configuration by parsing user-provided flags. Note plugin type so
	// that only applicable CLI flags are exposed and any plugin-specific
	// settings are applied.
	cfg, cfgErr := config.New(config.PluginType{ResourcePoolsMemory: true})
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case cfgErr != nil:
		// We're using the standalone Err function from rs/zerolog/log as we
		// do not have a working configuration.
		zlog.Err(cfgErr).Msg("Error initializing application")
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateCRITICALLabel,
		)
		nagiosExitState.LastError = cfgErr
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	// Enable library-level logging if debug logging level is enabled app-wide
	if cfg.LoggingLevel == config.LogLevelDebug {
		vsphere.EnableLogging()
	}

	// Set context deadline equal to user-specified timeout value for plugin
	// runtime/execution.
	ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeout())
	defer cancel()

	// Record thresholds for use as Nagios "Long Service Output" content. This
	// content is shown in the detailed web UI and in notifications generated
	// by Nagios.
	nagiosExitState.CriticalThreshold = fmt.Sprintf(
		"%d%% usage of %d GB memory",
		cfg.ResourcePoolsMemoryUseCritical,
		cfg.ResourcePoolsMemoryMaxAllowed,
	)

	nagiosExitState.WarningThreshold = fmt.Sprintf(
		"%d%% usage of %d GB memory",
		cfg.ResourcePoolsMemoryUseWarning,
		cfg.ResourcePoolsMemoryMaxAllowed,
	)

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		nagiosExitState.BrandingCallback = config.Branding("Notification generated by ")
	}

	// Setup logger with details showing actual user-specified CLI flag
	// values.
	log := cfg.Log.With().
		Str("included_resource_pools", cfg.IncludedResourcePools.String()).
		Str("excluded_resource_pools", cfg.ExcludedResourcePools.String()).
		Int("max_memory_usage_allowed", cfg.ResourcePoolsMemoryMaxAllowed).
		Int("memory_usage_critical", cfg.ResourcePoolsMemoryUseCritical).
		Int("memory_usage_warning", cfg.ResourcePoolsMemoryUseWarning).
		Logger()

	log.Debug().Msgf(
		"Explicitly excluding %q default/root/parent Resource Pool from evaluation",
		vsphere.ParentResourcePool,
	)

	// Explicitly ignore the default `Resources` resource pool so that we only
	// use the Resource Pools specified by the sysadmin.
	if err := cfg.ExcludedResourcePools.Set(vsphere.ParentResourcePool); err != nil {
		log.Err(cfgErr).Msg("Error excluding default Resource Pool from evaluation")
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error excluding default Resources Pool from evaluation",
			nagios.StateCRITICALLabel,
		)
		nagiosExitState.LastError = err
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	// Redefine logger, now with explicit exclusion added for parent resource
	// pool.
	log = cfg.Log.With().
		Str("included_resource_pools", cfg.IncludedResourcePools.String()).
		Str("excluded_resource_pools", cfg.ExcludedResourcePools.String()).
		Int("max_memory_usage_allowed", cfg.ResourcePoolsMemoryMaxAllowed).
		Int("memory_usage_critical", cfg.ResourcePoolsMemoryUseCritical).
		Int("memory_usage_warning", cfg.ResourcePoolsMemoryUseWarning).
		Logger()

	log.Debug().Msgf(
		"Successfully excluded %q Resource Pool from evaluation",
		vsphere.ParentResourcePool,
	)

	log.Debug().Msg("Logging into vSphere environment")
	c, loginErr := vsphere.Login(
		ctx, cfg.Server, cfg.Port, cfg.TrustCert,
		cfg.Username, cfg.Domain, cfg.Password,
		cfg.UserAgent(),
	)
	if loginErr != nil {
		log.Error().Err(loginErr).Msgf("error logging into %s", cfg.Server)

		nagiosExitState.LastError = loginErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error logging into %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Successfully logged into vSphere environment")

	defer func() {
		if err := c.Logout(ctx); err != nil {
			log.Error().
				Err(err).
				Msg("failed to logout")
		}
	}()

	// At this point we're logged in, ready to retrieve a list of VMs. If
	// specified, we should limit VMs based on include/exclude lists. First,
	// we'll make sure that all specified resource pools actually exist in the
	// vSphere environment.

	log.Debug().Msg("Validating resource pools")
	validateErr := vsphere.ValidateRPs(ctx, c.Client, cfg.IncludedResourcePools, cfg.ExcludedResourcePools)
	if validateErr != nil {
		log.Error().Err(validateErr).Msg("error validating include/exclude lists")

		nagiosExitState.LastError = validateErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error validating include/exclude lists",
			nagios.StateCRITICALLabel,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	log.Debug().Msg("Retrieving eligible resource pools")
	resourcePools, getRPsErr := vsphere.GetEligibleRPs(
		ctx,
		c.Client,
		cfg.IncludedResourcePools,
		cfg.ExcludedResourcePools,
		true,
	)
	if getRPsErr != nil {
		log.Error().Err(getRPsErr).Msg(
			"error retrieving list of resource pools",
		)

		nagiosExitState.LastError = getRPsErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving list of resource pools from %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	rpNames := make([]string, 0, len(resourcePools))
	for _, rp := range resourcePools {
		rpNames = append(rpNames, rp.Name)
	}

	log.Debug().
		Str("resource_pools", strings.Join(rpNames, ", ")).
		Msg("")

	aggregateRPStats, rpStatsErr := vsphere.ResourcePoolStats(ctx, c.Client, resourcePools)
	if rpStatsErr != nil {
		log.Error().Err(rpStatsErr).Msg(
			"error retrieving stats for resource pools",
		)

		nagiosExitState.LastError = rpStatsErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving stats for resource pools from %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	clusterMemoryInBytes, getMemErr := vsphere.GetHostSystemsTotalMemory(ctx, c.Client, false)
	if getMemErr != nil {
		log.Error().Err(getMemErr).Msg(
			"error retrieving hosts memory capacity",
		)

		nagiosExitState.LastError = getMemErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving memory capacity of hosts from %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	memoryPercentageUsedOfClusterCapacity := vsphere.MemoryUsedPercentage(
		aggregateRPStats.MemoryUsageInBytes,
		clusterMemoryInBytes,
	)

	log.Debug().
		Int64("cluster_memory_bytes", clusterMemoryInBytes).
		Str("cluster_memory_hr", units.ByteSize(clusterMemoryInBytes).String()).
		Float64("percent_memory_used_from_cluster_raw", memoryPercentageUsedOfClusterCapacity).
		Str("percent_memory_used_from_cluster_hr", fmt.Sprintf("%0.2f", memoryPercentageUsedOfClusterCapacity)).
		Msg("")

	log.Debug().
		Int64("aggregate_memory_usage_bytes", aggregateRPStats.MemoryUsageInBytes).
		Str("aggregate_memory_usage_hr", units.ByteSize(aggregateRPStats.MemoryUsageInBytes).String()).
		Msg("Finished evaluating Resource Pool memory usage")

	memoryUsageMaxInBytes := (int64(cfg.ResourcePoolsMemoryMaxAllowed) * units.GB)
	memoryPercentageUsedOfAllowed := vsphere.MemoryUsedPercentage(aggregateRPStats.MemoryUsageInBytes, memoryUsageMaxInBytes)
	var memoryRemainingInBytes int64

	switch {
	case aggregateRPStats.MemoryUsageInBytes > memoryUsageMaxInBytes:
		memoryRemainingInBytes = 0
	default:
		memoryRemainingInBytes = memoryUsageMaxInBytes - aggregateRPStats.MemoryUsageInBytes
	}

	log.Debug().
		Str("memory_usage", fmt.Sprintf("%.2f%%", memoryPercentageUsedOfAllowed)).
		Int64("memory_remaining_bytes", memoryRemainingInBytes).
		Str("memory_remaining_hr", units.ByteSize(memoryRemainingInBytes).String()).
		Int64("max_allowed_memory_bytes", memoryUsageMaxInBytes).
		Str("max_allowed_memory_bytes_hr", units.ByteSize(memoryUsageMaxInBytes).String()).
		Msg("memory usage")

	log.Debug().Msg("Retrieving vms from eligible resource pools")
	rpEntityVals := make([]mo.ManagedEntity, 0, len(resourcePools))
	for i := range resourcePools {
		rpEntityVals = append(rpEntityVals, resourcePools[i].ManagedEntity)
	}
	vms, getVMsErr := vsphere.GetVMsFromContainer(ctx, c.Client, true, rpEntityVals...)
	if getVMsErr != nil {
		log.Error().Err(getVMsErr).Msg(
			"error retrieving list of VMs from resource pools list",
		)

		nagiosExitState.LastError = getVMsErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving list of VMs from resource pools list",
			nagios.StateCRITICALLabel,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	log.Debug().Msg("Compiling Performance Data details")

	pd := []nagios.PerformanceData{
		// The `time` (runtime) metric is appended at plugin exit, so do not
		// duplicate it here.
		{
			Label: "vms",
			Value: fmt.Sprintf("%d", len(vms)),
		},
		{
			Label:             "memory_usage",
			Value:             fmt.Sprintf("%.2f", memoryPercentageUsedOfAllowed),
			UnitOfMeasurement: "%",
			Warn:              fmt.Sprintf("%d", cfg.ResourcePoolsMemoryUseWarning),
			Crit:              fmt.Sprintf("%d", cfg.ResourcePoolsMemoryUseCritical),
		},
		{
			Label:             "memory_used",
			Value:             fmt.Sprintf("%d", aggregateRPStats.MemoryUsageInBytes),
			UnitOfMeasurement: "B",
		},
		{
			Label:             "memory_remaining",
			Value:             fmt.Sprintf("%d", memoryRemainingInBytes),
			UnitOfMeasurement: "B",
		},
		{
			Label:             "memory_ballooned",
			Value:             fmt.Sprintf("%d", aggregateRPStats.BalloonedMemoryInBytes),
			UnitOfMeasurement: "B",
		},
		{
			Label:             "memory_swapped",
			Value:             fmt.Sprintf("%d", aggregateRPStats.SwappedMemoryInBytes),
			UnitOfMeasurement: "B",
		},
		{
			Label: "resource_pools_excluded",
			Value: fmt.Sprintf("%d", len(cfg.ExcludedResourcePools)),
		},
		{
			Label: "resource_pools_included",
			Value: fmt.Sprintf("%d", len(cfg.IncludedResourcePools)),
		},
		{
			Label: "resource_pools_evaluated",
			Value: fmt.Sprintf("%d", len(resourcePools)),
		},
	}

	// Update logger with new performance data related fields
	log = log.With().
		Int("vms_total", len(vms)).
		Str("memory_usage", fmt.Sprintf("%.2f%%", memoryPercentageUsedOfAllowed)).
		Int64("memory_used", aggregateRPStats.MemoryUsageInBytes).
		Int64("memory_remaining_bytes", memoryRemainingInBytes).
		Str("memory_remaining_hr", units.ByteSize(memoryRemainingInBytes).String()).
		Int64("memory_ballooned_bytes", aggregateRPStats.BalloonedMemoryInBytes).
		Str("memory_ballooned_hr", aggregateRPStats.BalloonedMemoryHR()).
		Int64("memory_swapped_bytes", aggregateRPStats.SwappedMemoryInBytes).
		Str("memory_swapped_hr", aggregateRPStats.SwappedMemoryHR()).
		Int64("max_allowed_memory_bytes", memoryUsageMaxInBytes).
		Str("max_allowed_memory_bytes_hr", units.ByteSize(memoryUsageMaxInBytes).String()).
		Int("resource_pools_evaluated", len(resourcePools)).
		Logger()

	switch {
	case memoryPercentageUsedOfAllowed > float64(cfg.ResourcePoolsMemoryUseCritical):

		log.Error().Msg("memory usage critical")

		nagiosExitState.LastError = vsphere.ErrResourcePoolMemoryUsageThresholdCrossed

		nagiosExitState.ServiceOutput = vsphere.RPMemoryUsageOneLineCheckSummary(
			nagios.StateCRITICALLabel,
			aggregateRPStats.MemoryUsageInBytes,
			memoryUsageMaxInBytes,
			clusterMemoryInBytes,
			resourcePools,
		)

		nagiosExitState.LongServiceOutput = vsphere.ResourcePoolsMemoryReport(
			c.Client,
			memoryUsageMaxInBytes,
			clusterMemoryInBytes,
			cfg.IncludedResourcePools,
			cfg.ExcludedResourcePools,
			resourcePools,
			vms,
		)

		if err := nagiosExitState.AddPerfData(false, pd...); err != nil {
			log.Error().
				Err(err).
				Msg("failed to add performance data")
		}

		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return

	case memoryPercentageUsedOfAllowed > float64(cfg.ResourcePoolsMemoryUseWarning):

		log.Error().Msg("memory usage warning")

		nagiosExitState.LastError = vsphere.ErrResourcePoolMemoryUsageThresholdCrossed

		nagiosExitState.ServiceOutput = vsphere.RPMemoryUsageOneLineCheckSummary(
			nagios.StateWARNINGLabel,
			aggregateRPStats.MemoryUsageInBytes,
			memoryUsageMaxInBytes,
			clusterMemoryInBytes,
			resourcePools,
		)

		nagiosExitState.LongServiceOutput = vsphere.ResourcePoolsMemoryReport(
			c.Client,
			memoryUsageMaxInBytes,
			clusterMemoryInBytes,
			cfg.IncludedResourcePools,
			cfg.ExcludedResourcePools,
			resourcePools,
			vms,
		)

		if err := nagiosExitState.AddPerfData(false, pd...); err != nil {
			log.Error().
				Err(err).
				Msg("failed to add performance data")
		}

		nagiosExitState.ExitStatusCode = nagios.StateWARNINGExitCode

		return

	default:

		log.Debug().Msg("memory usage ok")

		nagiosExitState.LastError = nil

		nagiosExitState.ServiceOutput = vsphere.RPMemoryUsageOneLineCheckSummary(
			nagios.StateOKLabel,
			aggregateRPStats.MemoryUsageInBytes,
			memoryUsageMaxInBytes,
			clusterMemoryInBytes,
			resourcePools,
		)

		nagiosExitState.LongServiceOutput = vsphere.ResourcePoolsMemoryReport(
			c.Client,
			memoryUsageMaxInBytes,
			clusterMemoryInBytes,
			cfg.IncludedResourcePools,
			cfg.ExcludedResourcePools,
			resourcePools,
			vms,
		)

		if err := nagiosExitState.AddPerfData(false, pd...); err != nil {
			log.Error().
				Err(err).
				Msg("failed to add performance data")
		}

		nagiosExitState.ExitStatusCode = nagios.StateOKExitCode

		return

	}

}
