// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-vmware
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/atc0005/go-nagios"
	"github.com/vmware/govmomi/vim25/mo"

	"github.com/atc0005/check-vmware/internal/config"
	"github.com/atc0005/check-vmware/internal/vsphere"

	zlog "github.com/rs/zerolog/log"
)

func main() {

	// Start the timer. We'll use this to emit the plugin runtime as a
	// performance data metric.
	pluginStart := time.Now()

	// Set initial "state" as valid, adjust as we go.
	var nagiosExitState = nagios.ExitState{
		LastError:      nil,
		ExitStatusCode: nagios.StateOKExitCode,
	}

	// defer this from the start so it is the last deferred function to run
	defer nagiosExitState.ReturnCheckResults()

	// Collect last minute details just before ending plugin execution.
	defer func(exitState *nagios.ExitState, start time.Time) {

		// Record plugin runtime, emit this metric regardless of exit
		// point/cause.
		runtimeMetric := nagios.PerformanceData{
			Label: "time",
			Value: fmt.Sprintf("%dms", time.Since(start).Milliseconds()),
		}
		if err := exitState.AddPerfData(false, runtimeMetric); err != nil {
			zlog.Error().
				Err(err).
				Msg("failed to add time (runtime) performance data metric")
		}

		// Annotate errors (if applicable) with additional context to aid in
		// troubleshooting.
		nagiosExitState.LastError = vsphere.AnnotateError(nagiosExitState.LastError)
	}(&nagiosExitState, pluginStart)

	// Disable library debug logging output by default
	// vsphere.EnableLogging()
	vsphere.DisableLogging()

	// Setup configuration by parsing user-provided flags. Note plugin type so
	// that only applicable CLI flags are exposed and any plugin-specific
	// settings are applied.
	cfg, cfgErr := config.New(config.PluginType{VirtualCPUsAllocation: true})
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case cfgErr != nil:
		// We're using the standalone Err function from rs/zerolog/log as we
		// do not have a working configuration.
		zlog.Err(cfgErr).Msg("Error initializing application")
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateCRITICALLabel,
		)
		nagiosExitState.LastError = cfgErr
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	// Enable library-level logging if debug logging level is enabled app-wide
	if cfg.LoggingLevel == config.LogLevelDebug {
		vsphere.EnableLogging()
	}

	// Set context deadline equal to user-specified timeout value for plugin
	// runtime/execution.
	ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeout())
	defer cancel()

	// Record thresholds for use as Nagios "Long Service Output" content. This
	// content is shown in the detailed web UI and in notifications generated
	// by Nagios.
	nagiosExitState.CriticalThreshold = fmt.Sprintf(
		"%d%% of %d vCPUs allocated",
		cfg.VCPUsAllocatedCritical,
		cfg.VCPUsMaxAllowed,
	)

	nagiosExitState.WarningThreshold = fmt.Sprintf(
		"%d%% of %d vCPUs allocated",
		cfg.VCPUsAllocatedWarning,
		cfg.VCPUsMaxAllowed,
	)

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		nagiosExitState.BrandingCallback = config.Branding("Notification generated by ")
	}

	log := cfg.Log.With().
		Str("included_resource_pools", cfg.IncludedResourcePools.String()).
		Str("excluded_resource_pools", cfg.ExcludedResourcePools.String()).
		Str("ignored_vms", cfg.IgnoredVMs.String()).
		Bool("eval_powered_off", cfg.PoweredOff).
		Int("max_vcpus_allowed", cfg.VCPUsMaxAllowed).
		Int("vcpus_critical_allocation", cfg.VCPUsAllocatedCritical).
		Int("vcpus_warning_allocation", cfg.VCPUsAllocatedWarning).
		Logger()

	log.Debug().Msg("Logging into vSphere environment")
	c, loginErr := vsphere.Login(
		ctx, cfg.Server, cfg.Port, cfg.TrustCert,
		cfg.Username, cfg.Domain, cfg.Password,
		cfg.UserAgent(),
	)
	if loginErr != nil {
		log.Error().Err(loginErr).Msgf("error logging into %s", cfg.Server)

		nagiosExitState.LastError = loginErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error logging into %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Successfully logged into vSphere environment")

	defer func() {
		if err := c.Logout(ctx); err != nil {
			log.Error().
				Err(err).
				Msg("failed to logout")
		}
	}()

	// At this point we're logged in, ready to retrieve a list of VMs. If
	// specified, we should limit VMs based on include/exclude lists. First,
	// we'll make sure that all specified resource pools actually exist in the
	// vSphere environment.

	log.Debug().Msg("Validating resource pools")
	validateErr := vsphere.ValidateRPs(ctx, c.Client, cfg.IncludedResourcePools, cfg.ExcludedResourcePools)
	if validateErr != nil {
		log.Error().Err(validateErr).Msg("error validating include/exclude lists")

		nagiosExitState.LastError = validateErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error validating include/exclude lists",
			nagios.StateCRITICALLabel,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	log.Debug().Msg("Retrieving eligible resource pools")
	resourcePools, getRPsErr := vsphere.GetEligibleRPs(
		ctx,
		c.Client,
		cfg.IncludedResourcePools,
		cfg.ExcludedResourcePools,
		true,
	)
	if getRPsErr != nil {
		log.Error().Err(getRPsErr).Msg(
			"error retrieving list of resource pools",
		)

		nagiosExitState.LastError = getRPsErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving list of resource pools from %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	rpNames := make([]string, 0, len(resourcePools))
	for _, rp := range resourcePools {
		rpNames = append(rpNames, rp.Name)
	}

	log.Debug().
		Str("resource_pools", strings.Join(rpNames, ", ")).
		Msg("")

	log.Debug().Msg("Retrieving vms from eligible resource pools")
	rpEntityVals := make([]mo.ManagedEntity, 0, len(resourcePools))
	for i := range resourcePools {
		rpEntityVals = append(rpEntityVals, resourcePools[i].ManagedEntity)
	}
	vms, getVMsErr := vsphere.GetVMsFromContainer(ctx, c.Client, true, rpEntityVals...)
	if getVMsErr != nil {
		log.Error().Err(getVMsErr).Msg(
			"error retrieving list of VMs from resource pools list",
		)

		nagiosExitState.LastError = getVMsErr
		nagiosExitState.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving list of VMs from resource pools list",
			nagios.StateCRITICALLabel,
		)
		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}

	log.Debug().
		Str("vms_evaluated", strings.Join(vsphere.VMNames(vms), ", ")).
		Msg("Evaluated Virtual Machines")

	log.Debug().Msg("Drop any VMs we've been asked to exclude from checks")
	filteredVMs, numVMsExcludedByName := vsphere.ExcludeVMsByName(vms, cfg.IgnoredVMs)

	log.Debug().
		Str("vms_filtered_by_name", strings.Join(vsphere.VMNames(filteredVMs), ", ")).
		Int("vms_excluded_by_name", numVMsExcludedByName).
		Msg("VMs after name filtering")

	log.Debug().Msg("Filter VMs to specified power state")
	filteredVMs, numVMsExcludedByPowerState := vsphere.FilterVMsByPowerState(filteredVMs, cfg.PoweredOff)

	log.Debug().
		Str("vms_filtered_by_power_state", strings.Join(vsphere.VMNames(filteredVMs), ", ")).
		Int("vms_excluded_by_power_state", numVMsExcludedByPowerState).
		Msg("VMs after power state filtering")

	// here we diverge from VMware Tools plugin

	var vCPUsAllocated int32
	for _, vm := range filteredVMs {
		vCPUsAllocated += vm.Summary.Config.NumCpu
		log.Debug().
			Str("vm_name", vm.Name).
			Int32("num_vcpu", vm.Summary.Config.NumCpu).
			Msg("")
	}

	log.Debug().
		Int32("vcpus_allocated", vCPUsAllocated).
		Msg("Finished counting vCPUs")

	vCPUsPercentageUsedOfAllowed := float32(vCPUsAllocated) / float32(cfg.VCPUsMaxAllowed) * 100
	var vCPUsRemaining int32

	switch {
	case vCPUsAllocated > int32(cfg.VCPUsMaxAllowed):
		vCPUsRemaining = 0
	default:
		vCPUsRemaining = int32(cfg.VCPUsMaxAllowed) - vCPUsAllocated
	}

	log.Debug().
		Float32("vcpus_usage", vCPUsPercentageUsedOfAllowed).
		Int32("vcpus_remaining", vCPUsRemaining).
		Msg("")

	log.Debug().Msg("Compiling Performance Data details")

	pd := []nagios.PerformanceData{
		// The `time` (runtime) metric is appended at plugin exit, so do not
		// duplicate it here.
		{
			Label: "vms",
			Value: fmt.Sprintf("%d", len(vms)),
		},
		{
			Label: "vms_excluded_by_name",
			Value: fmt.Sprintf("%d", numVMsExcludedByName),
		},
		{
			Label: "vms_excluded_by_power_state",
			Value: fmt.Sprintf("%d", numVMsExcludedByPowerState),
		},
		{
			Label:             "vcpus_usage",
			Value:             fmt.Sprintf("%.2f", vCPUsPercentageUsedOfAllowed),
			UnitOfMeasurement: "%",
			Warn:              fmt.Sprintf("%d", cfg.VCPUsAllocatedWarning),
			Crit:              fmt.Sprintf("%d", cfg.VCPUsAllocatedCritical),
		},
		{
			Label: "vcpus_used",
			Value: fmt.Sprintf("%d", vCPUsAllocated),
			Max:   fmt.Sprintf("%d", cfg.VCPUsMaxAllowed),
			Min:   fmt.Sprintf("%d", 0),
		},
		{
			Label: "vcpus_remaining",
			Value: fmt.Sprintf("%d", vCPUsRemaining),
			Max:   fmt.Sprintf("%d", cfg.VCPUsMaxAllowed),
			Min:   fmt.Sprintf("%d", 0),
		},
		{
			Label: "resource_pools_excluded",
			Value: fmt.Sprintf("%d", len(cfg.ExcludedResourcePools)),
		},
		{
			Label: "resource_pools_included",
			Value: fmt.Sprintf("%d", len(cfg.IncludedResourcePools)),
		},
		{
			Label: "resource_pools_evaluated",
			Value: fmt.Sprintf("%d", len(resourcePools)),
		},
	}

	// Update logger with new performance data related fields
	log = log.With().
		Int("vms_total", len(vms)).
		Int("vms_filtered", len(filteredVMs)).
		Int("vms_excluded_by_name", numVMsExcludedByName).
		Int("vms_excluded_by_power_state", numVMsExcludedByPowerState).
		Float32("vcpus_usage", vCPUsPercentageUsedOfAllowed).
		Int32("vcpus_used", vCPUsAllocated).
		Int32("vcpus_remaining", vCPUsRemaining).
		Int("resource_pools_evaluated", len(resourcePools)).
		Logger()

	log.Debug().Msg("Evaluating vCPU usage")
	switch {
	case vCPUsPercentageUsedOfAllowed > float32(cfg.VCPUsAllocatedCritical):

		log.Error().Msg("vCPUs allocation CRITICAL")

		nagiosExitState.LastError = vsphere.ErrVCPUsUsageThresholdCrossed

		nagiosExitState.ServiceOutput = vsphere.VirtualCPUsOneLineCheckSummary(
			nagios.StateCRITICALLabel,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
			filteredVMs,
			resourcePools,
		)

		nagiosExitState.LongServiceOutput = vsphere.VirtualCPUsReport(
			c.Client,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
			vms,
			filteredVMs,
			cfg.IgnoredVMs,
			cfg.PoweredOff,
			cfg.IncludedResourcePools,
			cfg.ExcludedResourcePools,
			resourcePools,
		)

		if err := nagiosExitState.AddPerfData(false, pd...); err != nil {
			log.Error().
				Err(err).
				Msg("failed to add performance data")
		}

		nagiosExitState.ExitStatusCode = nagios.StateCRITICALExitCode

		return

	case vCPUsPercentageUsedOfAllowed > float32(cfg.VCPUsAllocatedWarning):

		log.Error().Msg("vCPUs allocation WARNING")

		nagiosExitState.LastError = vsphere.ErrVCPUsUsageThresholdCrossed

		nagiosExitState.ServiceOutput = vsphere.VirtualCPUsOneLineCheckSummary(
			nagios.StateWARNINGLabel,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
			filteredVMs,
			resourcePools,
		)

		nagiosExitState.LongServiceOutput = vsphere.VirtualCPUsReport(
			c.Client,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
			vms,
			filteredVMs,
			cfg.IgnoredVMs,
			cfg.PoweredOff,
			cfg.IncludedResourcePools,
			cfg.ExcludedResourcePools,
			resourcePools,
		)

		if err := nagiosExitState.AddPerfData(false, pd...); err != nil {
			log.Error().
				Err(err).
				Msg("failed to add performance data")
		}

		nagiosExitState.ExitStatusCode = nagios.StateWARNINGExitCode

		return

	default:

		log.Debug().Msg("vCPUs allocation OK")

		nagiosExitState.LastError = nil

		nagiosExitState.ServiceOutput = vsphere.VirtualCPUsOneLineCheckSummary(
			nagios.StateOKLabel,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
			filteredVMs,
			resourcePools,
		)

		nagiosExitState.LongServiceOutput = vsphere.VirtualCPUsReport(
			c.Client,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
			vms,
			filteredVMs,
			cfg.IgnoredVMs,
			cfg.PoweredOff,
			cfg.IncludedResourcePools,
			cfg.ExcludedResourcePools,
			resourcePools,
		)

		if err := nagiosExitState.AddPerfData(false, pd...); err != nil {
			log.Error().
				Err(err).
				Msg("failed to add performance data")
		}

		nagiosExitState.ExitStatusCode = nagios.StateOKExitCode

		return

	}

}
