// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-vmware
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"context"
	"errors"
	"fmt"

	"github.com/atc0005/go-nagios"

	"github.com/atc0005/check-vmware/internal/config"
	"github.com/atc0005/check-vmware/internal/vsphere"

	zlog "github.com/rs/zerolog/log"
)

//go:generate go-winres make --product-version=git-tag --file-version=git-tag

func main() {

	plugin := nagios.NewPlugin()

	// defer this from the start so it is the last deferred function to run
	defer plugin.ReturnCheckResults()

	// Annotate all errors (if any) with remediation advice just before ending
	// plugin execution.
	defer vsphere.AnnotateError(plugin)

	// Setup configuration by parsing user-provided flags. Note plugin type so
	// that only applicable CLI flags are exposed and any plugin-specific
	// settings are applied.
	cfg, cfgErr := config.New(config.PluginType{VirtualCPUsAllocation: true})
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case cfgErr != nil:
		// We're using the standalone Err function from rs/zerolog/log as we
		// do not have a working configuration.
		zlog.Err(cfgErr).Msg("Error initializing application")
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateUNKNOWNLabel,
		)
		plugin.AddError(cfgErr)
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode

		return
	}

	// Enable library-level logging if debug or greater logging level is
	// enabled app-wide.
	handleLibraryLogging()

	// Set context deadline equal to user-specified timeout value for plugin
	// runtime/execution.
	ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeout())
	defer cancel()

	// Record thresholds for use as Nagios "Long Service Output" content. This
	// content is shown in the detailed web UI and in notifications generated
	// by Nagios.
	plugin.CriticalThreshold = fmt.Sprintf(
		"%d%% of %d vCPUs allocated",
		cfg.VCPUsAllocatedCritical,
		cfg.VCPUsMaxAllowed,
	)

	plugin.WarningThreshold = fmt.Sprintf(
		"%d%% of %d vCPUs allocated",
		cfg.VCPUsAllocatedWarning,
		cfg.VCPUsMaxAllowed,
	)

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		plugin.BrandingCallback = config.Branding("Notification generated by ")
	}

	log := cfg.Log.With().
		Str("included_resource_pools", cfg.IncludedResourcePools.String()).
		Str("excluded_resource_pools", cfg.ExcludedResourcePools.String()).
		Str("ignored_vms", cfg.IgnoredVMs.String()).
		Bool("eval_powered_off", cfg.PoweredOff).
		Int("max_vcpus_allowed", cfg.VCPUsMaxAllowed).
		Int("vcpus_critical_allocation", cfg.VCPUsAllocatedCritical).
		Int("vcpus_warning_allocation", cfg.VCPUsAllocatedWarning).
		Logger()

	log.Debug().Msg("Logging into vSphere environment")
	c, loginErr := vsphere.Login(
		ctx, cfg.Server, cfg.Port, cfg.TrustCert,
		cfg.Username, cfg.Domain, cfg.Password,
		cfg.UserAgent(),
	)
	if loginErr != nil {
		log.Error().Err(loginErr).Msgf("error logging into %s", cfg.Server)

		plugin.AddError(loginErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error logging into %q",
			nagios.StateCRITICALLabel,
			cfg.Server,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Successfully logged into vSphere environment")

	defer func() {
		if err := c.Logout(ctx); err != nil {
			log.Error().
				Err(err).
				Msg("failed to logout")
		}
	}()

	log.Debug().Msg("Filtering vms")
	vmsFilterOptions := vsphere.VMsFilterOptions{
		ResourcePoolsIncluded:       cfg.IncludedResourcePools,
		ResourcePoolsExcluded:       cfg.ExcludedResourcePools,
		FoldersIncluded:             cfg.IncludedFolders,
		FoldersExcluded:             cfg.ExcludedFolders,
		VirtualMachineNamesExcluded: cfg.IgnoredVMs,
		IncludePoweredOff:           cfg.PoweredOff,
	}
	vmsFilterResults, vmsFilterErr := vsphere.FilterVMs(
		ctx,
		c.Client,
		vmsFilterOptions,
	)
	if vmsFilterErr != nil {
		log.Error().Err(vmsFilterErr).Msg(
			"error filtering VMs",
		)

		plugin.AddError(vmsFilterErr)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error filtering VMs",
			nagios.StateCRITICALLabel,
		)
		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return
	}
	log.Debug().Msg("Finished filtering vms")

	// here we diverge from VMware Tools plugin

	var vCPUsAllocated int64
	for _, vm := range vmsFilterResults.VMsAfterFiltering() {
		vCPUsAllocated += int64(vm.Summary.Config.NumCpu)
		log.Debug().
			Str("vm_name", vm.Name).
			Int32("num_vcpu", vm.Summary.Config.NumCpu).
			Msg("")
	}

	log.Debug().
		Int64("vcpus_allocated", vCPUsAllocated).
		Msg("Finished counting vCPUs")

	vCPUsPercentageUsedOfAllowed := float64(vCPUsAllocated) / float64(cfg.VCPUsMaxAllowed) * 100
	var vCPUsRemaining int64

	switch {
	case vCPUsAllocated > int64(cfg.VCPUsMaxAllowed):
		vCPUsRemaining = 0
	default:
		vCPUsRemaining = int64(cfg.VCPUsMaxAllowed) - vCPUsAllocated
	}

	log.Debug().
		Float64("vcpus_usage", vCPUsPercentageUsedOfAllowed).
		Int64("vcpus_remaining", vCPUsRemaining).
		Msg("")

	log.Debug().Msg("Compiling Performance Data details")

	pd := append(
		vsphere.VMFilterResultsPerfData(vmsFilterResults),
		[]nagios.PerformanceData{
			// The `time` (runtime) metric is appended at plugin exit, so do not
			// duplicate it here.
			{
				Label:             "vcpus_usage",
				Value:             fmt.Sprintf("%.2f", vCPUsPercentageUsedOfAllowed),
				UnitOfMeasurement: "%",
				Warn:              fmt.Sprintf("%d", cfg.VCPUsAllocatedWarning),
				Crit:              fmt.Sprintf("%d", cfg.VCPUsAllocatedCritical),
			},
			{
				Label: "vcpus_used",
				Value: fmt.Sprintf("%d", vCPUsAllocated),
			},
			{
				Label: "vcpus_remaining",
				Value: fmt.Sprintf("%d", vCPUsRemaining),
			},
		}...,
	)

	if err := plugin.AddPerfData(false, pd...); err != nil {
		log.Error().
			Err(err).
			Msg("failed to add performance data")

		// Surface the error in plugin output.
		plugin.AddError(err)

		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Failed to process performance data metrics",
			nagios.StateUNKNOWNLabel,
		)

		return
	}

	// Update logger with new performance data related fields
	log = log.With().
		Int("resource_pools_evaluated", vmsFilterResults.NumRPsAfterFiltering()).
		Int("vms_total", vmsFilterResults.NumVMsAll()).
		Int("vms_after_filtering", vmsFilterResults.NumVMsAfterFiltering()).
		Int("vms_excluded_by_name", vmsFilterResults.NumVMsExcludedByName()).
		Int("vms_excluded_by_power_state", vmsFilterResults.NumVMsExcludedByPowerState()).
		Float64("vcpus_usage", vCPUsPercentageUsedOfAllowed).
		Int64("vcpus_used", vCPUsAllocated).
		Int64("vcpus_remaining", vCPUsRemaining).
		Logger()

	log.Debug().Msg("Evaluating vCPU usage")
	switch {
	case vCPUsPercentageUsedOfAllowed > float64(cfg.VCPUsAllocatedCritical):

		log.Error().Msg("vCPUs allocation CRITICAL")

		plugin.AddError(vsphere.ErrVCPUsUsageThresholdCrossed)

		plugin.ServiceOutput = vsphere.VirtualCPUsOneLineCheckSummary(
			nagios.StateCRITICALLabel,
			vmsFilterResults,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
		)

		plugin.LongServiceOutput = vsphere.VirtualCPUsReport(
			c.Client,
			vmsFilterOptions,
			vmsFilterResults,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
		)

		plugin.ExitStatusCode = nagios.StateCRITICALExitCode

		return

	case vCPUsPercentageUsedOfAllowed > float64(cfg.VCPUsAllocatedWarning):

		log.Error().Msg("vCPUs allocation WARNING")

		plugin.AddError(vsphere.ErrVCPUsUsageThresholdCrossed)

		plugin.ServiceOutput = vsphere.VirtualCPUsOneLineCheckSummary(
			nagios.StateWARNINGLabel,
			vmsFilterResults,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
		)

		plugin.LongServiceOutput = vsphere.VirtualCPUsReport(
			c.Client,
			vmsFilterOptions,
			vmsFilterResults,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
		)

		plugin.ExitStatusCode = nagios.StateWARNINGExitCode

		return

	default:

		log.Debug().Msg("vCPUs allocation OK")

		plugin.ServiceOutput = vsphere.VirtualCPUsOneLineCheckSummary(
			nagios.StateOKLabel,
			vmsFilterResults,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
		)

		plugin.LongServiceOutput = vsphere.VirtualCPUsReport(
			c.Client,
			vmsFilterOptions,
			vmsFilterResults,
			vCPUsAllocated,
			cfg.VCPUsMaxAllowed,
		)

		plugin.ExitStatusCode = nagios.StateOKExitCode

		return

	}

}
